name: CI
on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-22.04
    if: github.repository_owner == 'lukash'
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v4
      - uses: DeterminateSystems/flake-checker-action@v4
      - uses: rrbutani/use-nix-shell-action@v1
        with:
          flakes: nixpkgs#clang-tools_17, nixpkgs#gcc-arm-embedded-13, nixpkgs#gnumake, nixpkgs#lefthook, github:lukash/vesc_tool-flake/release_6_02

      - name: clang-format
        id: clang-format
        run: lefthook run clang-format-check

      - name: build
        # make this step run even if clang-format failed
        if: success() || (failure() && steps.clang-format.conclusion == 'failure')
        run: make -j
        working-directory: refloat/
